vm script updates

diff --git a/create-vm b/create-vm
--- a/create-vm
+++ b/create-vm
@@ -90,14 +90,12 @@ EOF
 virsh net-update --network default --command add --section dns-host --xml ${T}
 
 echo "Waiting for ${SNO} to start..."
-found=0
-while [ $found -eq 0 ]; do
-    virsh -q list --state-running 2>/dev/null | grep -q ${SNO}
-    if [ $? -eq 0 ]; then
-        found=1
-    else
-        sleep 1
+while true; do
+    state=$(virsh domstate ${SNO} 2>/dev/null)
+    if [ "${state}" == "running" ]; then
+        break
     fi
+    sleep 1
 done
 # Update /etc/hosts
 echo "Need to update /etc/hosts (sudo may prompt for password)"
@@ -106,14 +104,16 @@ ${IP} api.$C.$D ${SNO}
 EOF
 # Sometimes we get stuck here...
 echo "Waiting for ${SNO} to shutdown..."
-found=0
-while [ $found -eq 0 ]; do
-    virsh -q list --state-shutoff 2>/dev/null | grep -q ${SNO}
-    if [ $? -eq 0 ]; then
-        found=1
-    else
-        sleep 1
+while true; do
+    state=$(virsh domstate ${SNO} 2>/dev/null)
+    if [ "${state}" == "" ]; then
+        echo "VM ${SNO} not found"
+        exit 1
     fi
+    if [ "${state}" == "shut off" ]; then
+        break
+    fi
+    sleep 1
 done
 echo "Restarting ${SNO}..."
 virsh start ${SNO}
