Update name and mac
Fixes #1

* No more need for fixed MAC address
* Name of cluster comes from config.yaml now
* Fixed issue with ingress

diff --git a/delete-vm b/delete-vm
--- a/delete-vm
+++ b/delete-vm
@@ -2,23 +2,26 @@
 
 export LIBVIRT_DEFAULT_URI=qemu:///system
 
-virsh -q list --all 2>/dev/null | grep -q SNO
+SNO=${CLUSTERNAME:-$(cat config.yaml | yq .sno.name)}
+IP=
+virsh -q list --all 2>/dev/null | grep -q ${SNO}
 if [ $? -eq 0 ]; then
-    virsh undefine SNO
-    virsh -q list --state-running --state-paused 2>/dev/null | grep -q SNO
+    IP=$(virsh -q domifaddr ${SNO} --source arp 2>/dev/null | awk '{print $4}' | cut -d/ -f1)
+    if [ $? -ne 0 -o -z "${IP}" ]; then
+        echo "Unable to get IP address"
+    fi
+    virsh undefine ${SNO}
+    virsh -q list --state-running --state-paused 2>/dev/null | grep -q ${SNO}
     if [ $? -eq 0 ]; then
-        virsh shutdown --domain SNO --mode acpi
+        virsh shutdown --domain ${SNO} --mode acpi
     fi
 
-    virsh vol-delete SNO.qcow2 --pool default
+    virsh vol-delete ${SNO}.qcow2 --pool default
 else
-    echo "VM SNO not found"
+    echo "VM ${SNO} not found"
 fi
 
-# We need to get the IP address!
-MAC=00:11:22:33:44:55
-IP=$(virsh -q net-dhcp-leases default --mac ${MAC} 2>/dev/null | gawk '{print $5}' | cut -d/ -f1)
-if [ $? -eq 0 ]; then
+if [ -n "${IP}" ]; then
     virsh net-update --network default --command delete --section dns-host --xml "<host ip='${IP}'></host>"
 
     D=${BASEDOMAIN:-$(cat config.yaml | yq .sno.domain)}
